# Generated by Django 5.1.7 on 2025-03-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('weight', models.FloatField()),
                ('send_date', models.DateTimeField()),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('last_event_date', models.DateTimeField(blank=True, null=True)),
                ('last_event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
