# Generated by Django 5.1.7 on 2025-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitem',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
