# Generated by Django 5.1.7 on 2025-03-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_mailitem_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitem',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
