# Generated by Django 5.1.7 on 2025-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0004_eventstatus_remove_mailitem_last_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailitem',
            name='last_event_name',
        ),
        migrations.AddField(
            model_name='mailitem',
            name='last_event_name',
            field=models.JSONField(default=list),
        ),
    ]
