# Generated by Django 5.1.7 on 2025-03-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0005_remove_mailitem_last_event_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventStatus',
        ),
    ]
