# Generated by Django 5.1.7 on 2025-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0006_delete_eventstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
